In [28]:
import pandas as pd
from google.colab import files
import io

uploaded = files.upload()

Saving amit.xlsx to amit.xlsx

In [29]:
ps = pd.read_excel("amit.xlsx")

In [30]:
ps.head()

,Digi-Key Part Number,Manufacturer Part Number,Manufacturer,Description,Quantity Available,Unit Price (USD),Product Category,Package / Case,RoHS Status,Minimum Order Qty,Currency,Product URL,Datasheet URL,Internal Note,Last Updated,Warehouse,Catalog Batch,QA Flag
0,144-PS215M6233T-ND,PS-215M6233-T,Phoenix Contact,POWER MODULE 24V 40W,0,42.3225,Power Supplies,Axial,Unknown,100,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/ps_215m6233_t.pdf,verify pricing,2026-02-26,US West,BATCH-002,REVIEW
1,465-PS258F5394R-ND,PS-258F5394-R,Molex,POWER MODULE 24V 40W,733,0.2753,Power Supplies,QFP-48,RoHS Compliant,1,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/ps_258f5394_r.pdf,verify pricing,2024-04-11,EU Central,BATCH-010,REVIEW
2,169-C260U8249T-ND,C-260U8249-T,Infineon Technologies,CAP CER 0.1UF 50V X7R ±1%,0,1.7535,Capacitors,SOD-123,Not Applicable,5,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/c_260u8249_t.pdf,NaN,2025-10-04,US East,BATCH-029,NaN
3,467-D947N2192R-ND,D-947N2192-R,Würth Elektronik,TVS DIODE 5V UNIDIR,0,7.0559,Diodes,SMA,Not Applicable,1,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/d_947n2192_r.pdf,Legacy item,2024-07-03,US West,BATCH-029,REVIEW
4,956-OP719P9865S-ND,OP-719P9865-S,Murata Electronics,IC OPAMP GP 1 CIRCUIT 5SOT-23,0,93.5672,Operational Amplifiers,SMA,Unknown,25,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/op_719p9865_s.pdf,NaN,2025-01-17,Asia Pacific,BATCH-002,PASS

In [34]:
ps.shape

(5000, 18)

In [35]:
ps.head()

,Digi-Key Part Number,Manufacturer Part Number,Manufacturer,Description,Quantity Available,Unit Price (USD),Product Category,Package / Case,RoHS Status,Minimum Order Qty,Currency,Product URL,Datasheet URL,Internal Note,Last Updated,Warehouse,Catalog Batch,QA Flag
0,144-PS215M6233T-ND,PS-215M6233-T,Phoenix Contact,POWER MODULE 24V 40W,0,42.3225,Power Supplies,Axial,Unknown,100,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/ps_215m6233_t.pdf,verify pricing,2026-02-26,US West,BATCH-002,REVIEW
1,465-PS258F5394R-ND,PS-258F5394-R,Molex,POWER MODULE 24V 40W,733,0.2753,Power Supplies,QFP-48,RoHS Compliant,1,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/ps_258f5394_r.pdf,verify pricing,2024-04-11,EU Central,BATCH-010,REVIEW
2,169-C260U8249T-ND,C-260U8249-T,Infineon Technologies,CAP CER 0.1UF 50V X7R ±1%,0,1.7535,Capacitors,SOD-123,Not Applicable,5,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/c_260u8249_t.pdf,NaN,2025-10-04,US East,BATCH-029,NaN
3,467-D947N2192R-ND,D-947N2192-R,Würth Elektronik,TVS DIODE 5V UNIDIR,0,7.0559,Diodes,SMA,Not Applicable,1,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/d_947n2192_r.pdf,Legacy item,2024-07-03,US West,BATCH-029,REVIEW
4,956-OP719P9865S-ND,OP-719P9865-S,Murata Electronics,IC OPAMP GP 1 CIRCUIT 5SOT-23,0,93.5672,Operational Amplifiers,SMA,Unknown,25,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/op_719p9865_s.pdf,NaN,2025-01-17,Asia Pacific,BATCH-002,PASS

In [36]:
ps.head(10)

,Digi-Key Part Number,Manufacturer Part Number,Manufacturer,Description,Quantity Available,Unit Price (USD),Product Category,Package / Case,RoHS Status,Minimum Order Qty,Currency,Product URL,Datasheet URL,Internal Note,Last Updated,Warehouse,Catalog Batch,QA Flag
0,144-PS215M6233T-ND,PS-215M6233-T,Phoenix Contact,POWER MODULE 24V 40W,0,42.3225,Power Supplies,Axial,Unknown,100,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/ps_215m6233_t.pdf,verify pricing,2026-02-26,US West,BATCH-002,REVIEW
1,465-PS258F5394R-ND,PS-258F5394-R,Molex,POWER MODULE 24V 40W,733,0.2753,Power Supplies,QFP-48,RoHS Compliant,1,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/ps_258f5394_r.pdf,verify pricing,2024-04-11,EU Central,BATCH-010,REVIEW
2,169-C260U8249T-ND,C-260U8249-T,Infineon Technologies,CAP CER 0.1UF 50V X7R ±1%,0,1.7535,Capacitors,SOD-123,Not Applicable,5,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/c_260u8249_t.pdf,NaN,2025-10-04,US East,BATCH-029,NaN
3,467-D947N2192R-ND,D-947N2192-R,Würth Elektronik,TVS DIODE 5V UNIDIR,0,7.0559,Diodes,SMA,Not Applicable,1,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/d_947n2192_r.pdf,Legacy item,2024-07-03,US West,BATCH-029,REVIEW
4,956-OP719P9865S-ND,OP-719P9865-S,Murata Electronics,IC OPAMP GP 1 CIRCUIT 5SOT-23,0,93.5672,Operational Amplifiers,SMA,Unknown,25,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/op_719p9865_s.pdf,NaN,2025-01-17,Asia Pacific,BATCH-002,PASS
5,309-C293V2022-ND,C-293V2022,Analog Devices,CAP CER 10UF 16V X5R,0,0.1447,Capacitors,Through Hole,RoHS Compliant,25,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/c_293v2022.pdf,Reviewed,2023-10-17,US Central,BATCH-035,PASS
6,331-C937F6425R-ND,C-937F6425-R,NaN,CAP FILM 1UF 100V HIGH RELIABILITY,143448,23.6168,Capacitors,SMA,RoHS3 Compliant,25,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/c_937f6425_r.pdf,NaN,2026-06-04,US East,BATCH-037,REVIEW
7,474-L321S5497T-ND,L-321S5497-T,Yageo,FIXED IND 10UH 1.2A,93980,22.4024,Inductors,BGA-64,RoHS Compliant,5,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/l_321s5497_t.pdf,Check alternate packaging,2024-12-21,Asia Pacific,BATCH-002,PASS
8,538-D183D4245R-ND,D-183D4245-R,KYOCERA AVX,DIODE SCHOTTKY 40V 1A,0,71.6037,Diodes,0805 (2012 Metric),RoHS3 Compliant,10,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/d_183d4245_r.pdf,Legacy item,2025-11-13,EU Central,BATCH-001,REVIEW
9,475-CBL639G1997R-ND,CBL-639G1997-R,Bourns,JUMPER WIRE 150MM,0,104.3658,Cables,DIP-8,RoHS Compliant,25,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/cbl_639g1997_r.pdf,NaN,2026-08-26,Asia Pacific,BATCH-036,PASS

In [38]:
ps.columns.tolist()

['Digi-Key Part Number',
 'Manufacturer Part Number',
 'Manufacturer',
 'Description',
 'Quantity Available',
 'Unit Price (USD)',
 'Product Category',
 'Package / Case',
 'RoHS Status',
 'Minimum Order Qty',
 'Currency',
 'Product URL',
 'Datasheet URL',
 'Internal Note',
 'Last Updated',
 'Warehouse',
 'Catalog Batch',
 'QA Flag']

In [39]:
ps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Digi-Key Part Number      4965 non-null   object
 1   Manufacturer Part Number  4941 non-null   object
 2   Manufacturer              4929 non-null   object
 3   Description               4951 non-null   object
 4   Quantity Available        4905 non-null   object
 5   Unit Price (USD)          4913 non-null   object
 6   Product Category          4942 non-null   object
 7   Package / Case            4948 non-null   object
 8   RoHS Status               5000 non-null   object
 9   Minimum Order Qty         5000 non-null   int64
 10  Currency                  5000 non-null   object
 11  Product URL               5000 non-null   object
 12  Datasheet URL             5000 non-null   object
 13  Internal Note             3102 non-null   object
 14  Last Updated              5000 non-null   datetime64[ns]
 15  Warehouse                 5000 non-null   object
 16  Catalog Batch             5000 non-null   object
 17  QA Flag                   3983 non-null   object
dtypes: datetime64[ns](1), int64(1), object(16)
memory usage: 703.3+ KB

In [42]:
ps.isna().sum().sort_values(ascending=False)

Internal Note               1898
QA Flag                     1017
Quantity Available            95
Unit Price (USD)              87
Manufacturer                  71
Manufacturer Part Number      59
Product Category              58
Package / Case                52
Description                   49
Digi-Key Part Number          35
Minimum Order Qty              0
RoHS Status                    0
Product URL                    0
Currency                       0
Datasheet URL                  0
Last Updated                   0
Warehouse                      0
Catalog Batch                  0
dtype: int64

In [45]:
ps.duplicated().sum()

np.int64(100)

In [46]:
ps.shape

(5000, 18)

In [47]:
ps.columns.tolist()

['Digi-Key Part Number',
 'Manufacturer Part Number',
 'Manufacturer',
 'Description',
 'Quantity Available',
 'Unit Price (USD)',
 'Product Category',
 'Package / Case',
 'RoHS Status',
 'Minimum Order Qty',
 'Currency',
 'Product URL',
 'Datasheet URL',
 'Internal Note',
 'Last Updated',
 'Warehouse',
 'Catalog Batch',
 'QA Flag']

In [48]:
ps_clean = ps.copy()

In [49]:
keep_columns = [
    "Digi-Key Part Number",
    "Manufacturer Part Number",
    "Manufacturer",
    "Description",
    "Quantity Available",
    "Unit Price (USD)",
    "Product Category",
    "Package / Case",
    "RoHS Status",
    "Minimum Order Qty",
    "Currency",
    "Product URL",
    "Datasheet URL",
    "Last Updated",
    "Warehouse"
]

In [50]:
ps_clean = ps_clean[keep_columns].copy()

In [51]:
ps_clean.shape

(5000, 15)

In [52]:
ps_clean.head()

,Digi-Key Part Number,Manufacturer Part Number,Manufacturer,Description,Quantity Available,Unit Price (USD),Product Category,Package / Case,RoHS Status,Minimum Order Qty,Currency,Product URL,Datasheet URL,Last Updated,Warehouse
0,144-PS215M6233T-ND,PS-215M6233-T,Phoenix Contact,POWER MODULE 24V 40W,0,42.3225,Power Supplies,Axial,Unknown,100,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/ps_215m6233_t.pdf,2026-02-26,US West
1,465-PS258F5394R-ND,PS-258F5394-R,Molex,POWER MODULE 24V 40W,733,0.2753,Power Supplies,QFP-48,RoHS Compliant,1,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/ps_258f5394_r.pdf,2024-04-11,EU Central
2,169-C260U8249T-ND,C-260U8249-T,Infineon Technologies,CAP CER 0.1UF 50V X7R ±1%,0,1.7535,Capacitors,SOD-123,Not Applicable,5,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/c_260u8249_t.pdf,2025-10-04,US East
3,467-D947N2192R-ND,D-947N2192-R,Würth Elektronik,TVS DIODE 5V UNIDIR,0,7.0559,Diodes,SMA,Not Applicable,1,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/d_947n2192_r.pdf,2024-07-03,US West
4,956-OP719P9865S-ND,OP-719P9865-S,Murata Electronics,IC OPAMP GP 1 CIRCUIT 5SOT-23,0,93.5672,Operational Amplifiers,SMA,Unknown,25,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/op_719p9865_s.pdf,2025-01-17,Asia Pacific

In [53]:
ps_clean.duplicated().sum()

np.int64(100)

In [54]:
duplicates = ps_clean[ps_clean.duplicated(keep=False)]

duplicates.head(10)

,Digi-Key Part Number,Manufacturer Part Number,Manufacturer,Description,Quantity Available,Unit Price (USD),Product Category,Package / Case,RoHS Status,Minimum Order Qty,Currency,Product URL,Datasheet URL,Last Updated,Warehouse
14,360-XTAL947V2200TR-ND,XTAL-947V2200-TR,onsemi,CRYSTAL 32.768KHZ,877066,0.1717,Oscillators,SOT-23,RoHS Compliant,10,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/xtal_947v2200_t...,2025-01-14,US East
75,665-F845P8357T-ND,F-845P8357-T,Analog Devices,FUSE BOARD MOUNT 2A 250V,7513,21.8473,Fuses,DIP-8,RoHS Compliant,100,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/f_845p8357_t.pdf,2025-07-29,US East
95,748-OP223W4375TR-ND,OP-223W4375-TR,STMicroelectronics,IC OPAMP GP 1 CIRCUIT 5SOT-23,77,0.0121,Operational Amplifiers,SOD-123,Unknown,1,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/op_223w4375_tr.pdf,2026-03-12,US East
109,417-MCU144H8209T-ND,MCU-144H8209-T,EPCOS,IC MCU 32BIT 128KB FLASH 48LQFP,68,8.0645,Microcontrollers,BGA-64,Unknown,25,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/mcu_144h8209_t.pdf,2026-03-17,US East
181,669-L921K3337R-ND,L-921K3337-R,Nichicon,RF IND 100NH ±1%,0,11.8842,Inductors,QFP-48,RoHS3 Compliant,10,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/l_921k3337_r.pdf,2025-09-16,US Central
213,797-J801P5629S-ND,J-801P5629-S,KYOCERA AVX,CONN HEADER 10POS 2.54MM,0,3.1379,Connectors,TO-220-3,Unknown,25,USD,https://example.com/digikey-practice/products/35,https://example.com/datasheets/j_801p5629_s.pdf,2023-06-02,US East
216,197-SNS511G2604TR-ND,SNS-511G2604-TR,Phoenix Contact,SENSOR HALL EFFECT LATCH,87,0.1013,Sensors,SOIC-8,RoHS3 Compliant,10,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/sns_511g2604_tr...,2023-10-15,EU Central
225,247-REG695B7327TR-ND,REG-695B7327-TR,Murata Electronics,IC REG BUCK ADJ 2A 8SOIC,0,0.509,Voltage Regulators,QFP-48,Not Applicable,5,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/reg_695b7327_tr...,2024-11-10,US West
234,532-SW595R3265TR-ND,SW-595R3265-TR,Infineon Technologies,SWITCH SLIDE SPDT 300MA,0,8.8245,Switches,QFP-48,Not Applicable,10,USD,https://example.com/digikey-practice/products/211,https://example.com/datasheets/sw_595r3265_tr.pdf,2026-07-11,EU Central
286,702-SW373W7739R-ND,SW-373W7739-R,ROHM Semiconductor,SWITCH SLIDE SPDT 300MA,0,0.025,Switches,TSSOP-16,RoHS3 Compliant,1,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/sw_373w7739_r.pdf,2023-06-05,US East

In [55]:
rows_before = len(ps_clean)

ps_clean = ps_clean.drop_duplicates()

rows_after = len(ps_clean)

print("Rows before cleaning:", rows_before)
print("Rows after cleaning:", rows_after)
print("Duplicate rows removed:", rows_before - rows_after)

Rows before cleaning: 5000
Rows after cleaning: 4900
Duplicate rows removed: 100

In [56]:
ps_clean.isna().sum()

Digi-Key Part Number        35
Manufacturer Part Number    57
Manufacturer                69
Description                 48
Quantity Available          95
Unit Price (USD)            87
Product Category            58
Package / Case              52
RoHS Status                  0
Minimum Order Qty            0
Currency                     0
Product URL                  0
Datasheet URL                0
Last Updated                 0
Warehouse                    0
dtype: int64

In [57]:
missing_summary = pd.DataFrame({
    "Missing Values": ps_clean.isna().sum(),
    "Missing Percentage": (ps_clean.isna().mean() * 100).round(2)
})

missing_summary.sort_values(
    by="Missing Percentage",
    ascending=False
)

                          Missing Values  Missing Percentage
Quantity Available                    95                1.94
Unit Price (USD)                      87                1.78
Manufacturer                          69                1.41
Product Category                      58                1.18
Manufacturer Part Number              57                1.16
Package / Case                        52                1.06
Description                           48                0.98
Digi-Key Part Number                  35                0.71
RoHS Status                            0                0.00
Minimum Order Qty                      0                0.00
Currency                               0                0.00
Product URL                            0                0.00
Datasheet URL                          0                0.00
Last Updated                           0                0.00
Warehouse                              0                0.00

In [58]:
ps_clean = ps_clean.replace(r'^\s*$', pd.NA, regex=True)

In [59]:
ps_clean.isna().sum().sort_values(ascending=False)

Quantity Available          95
Description                 87
Unit Price (USD)            87
Manufacturer                69
Product Category            58
Manufacturer Part Number    57
Package / Case              52
Digi-Key Part Number        50
RoHS Status                  0
Minimum Order Qty            0
Currency                     0
Product URL                  0
Datasheet URL                0
Last Updated                 0
Warehouse                    0
dtype: int64

In [60]:
ps_clean["Digi-Key Part Number"].isna().sum()

np.int64(50)

In [61]:
ps_clean.loc[
    ps_clean["Digi-Key Part Number"].isna(),
    [
        "Digi-Key Part Number",
        "Manufacturer Part Number",
        "Manufacturer",
        "Description"
    ]
].head(10)

,Digi-Key Part Number,Manufacturer Part Number,Manufacturer,Description
44,<NA>,PS-TEST0013,Littelfuse,AC/DC CONVERTER 12V 2A
233,<NA>,L-TEST0028,EPCOS,FIXED IND 47UH 750MA
532,NaN,SW-TEST0048,Vishay,SWITCH SLIDE SPDT 300MA
598,NaN,XTAL-TEST0020,ROHM Semiconductor,CRYSTAL 16MHZ 18PF SMD
675,NaN,LED-TEST0029,STMicroelectronics,LED BLUE 470NM THROUGH HOLE
681,NaN,XTAL-TEST0044,Nichicon,CRYSTAL 16MHZ 18PF SMD
683,<NA>,F-TEST0031,Würth Elektronik,FUSE BOARD MOUNT 2A 250V
721,<NA>,J-TEST0041,Molex,CONN TERMINAL BLOCK 3POS
743,<NA>,F-TEST0022,STMicroelectronics,RESETTABLE PTC 500MA
744,NaN,MCU-TEST0023,Bourns,IC MCU 32BIT 128KB FLASH 48LQFP

In [62]:
ps_clean["Digi-Key Part Number"].isna().sum()

np.int64(50)

In [63]:
ps_clean["Missing Digi-Key Part Number"] = (
    ps_clean["Digi-Key Part Number"].isna()
)

In [64]:
ps_clean[
    ps_clean["Missing Digi-Key Part Number"]
].head(10)

,Digi-Key Part Number,Manufacturer Part Number,Manufacturer,Description,Quantity Available,Unit Price (USD),Product Category,Package / Case,RoHS Status,Minimum Order Qty,Currency,Product URL,Datasheet URL,Last Updated,Warehouse,Missing Digi-Key Part Number
44,<NA>,PS-TEST0013,Littelfuse,AC/DC CONVERTER 12V 2A,NaN,1.25,Power Supplies,Through Hole,RoHS Compliant,5,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/test-13.pdf,2025-12-16,EU Central,True
233,<NA>,L-TEST0028,EPCOS,FIXED IND 47UH 750MA,NaN,0.95,Inductors,BGA-64,RoHS Compliant,5,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/test-28.pdf,2025-04-11,US Central,True
532,NaN,SW-TEST0048,Vishay,SWITCH SLIDE SPDT 300MA,NaN,TBD,Switches,Surface Mount,RoHS Compliant,10,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/test-48.pdf,2025-01-17,Asia Pacific,True
598,NaN,XTAL-TEST0020,ROHM Semiconductor,CRYSTAL 16MHZ 18PF SMD,NaN,1.25,Oscillators,QFP-48,Unknown,1,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/test-20.pdf,2026-03-26,US Central,True
675,NaN,LED-TEST0029,STMicroelectronics,LED BLUE 470NM THROUGH HOLE,NaN,0.95,LEDs,SOT-23,Not Applicable,10,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/test-29.pdf,2026-04-24,Asia Pacific,True
681,NaN,XTAL-TEST0044,Nichicon,CRYSTAL 16MHZ 18PF SMD,100,1.25,Oscillators,SOIC-8,Unknown,1,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/test-44.pdf,2026-07-30,US Central,True
683,<NA>,F-TEST0031,Würth Elektronik,FUSE BOARD MOUNT 2A 250V,NaN,TBD,Fuses,0805 (2012 Metric),RoHS Compliant,5,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/test-31.pdf,2024-02-05,US East,True
721,<NA>,J-TEST0041,Molex,CONN TERMINAL BLOCK 3POS,NaN,0.95,Connectors,QFP-48,Not Applicable,1,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/test-41.pdf,2025-06-21,US West,True
743,<NA>,F-TEST0022,STMicroelectronics,RESETTABLE PTC 500MA,NaN,NaN,Fuses,TSSOP-16,RoHS Compliant,10,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/test-22.pdf,2024-02-20,EU Central,True
744,NaN,MCU-TEST0023,Bourns,IC MCU 32BIT 128KB FLASH 48LQFP,100,0.95,Microcontrollers,Through Hole,Unknown,10,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/test-23.pdf,2024-12-27,Asia Pacific,True

In [65]:
# Remove unwanted spaces, dollar signs and commas
ps_clean["Unit Price (USD)"] = (
    ps_clean["Unit Price (USD)"]
    .astype("string")
    .str.strip()
    .str.replace(r"[$,]", "", regex=True)
)

# Convert price values into numeric format
ps_clean["Unit Price (USD)"] = pd.to_numeric(
    ps_clean["Unit Price (USD)"],
    errors="coerce"
)

In [66]:
ps_clean["Quantity Available"] = (
    ps_clean["Quantity Available"]
    .astype("string")
    .str.strip()
    .str.replace(",", "", regex=False)
)

ps_clean["Quantity Available"] = pd.to_numeric(
    ps_clean["Quantity Available"],
    errors="coerce"
)

In [67]:
ps_clean[["Unit Price (USD)", "Quantity Available"]].dtypes

Unit Price (USD)      Float64
Quantity Available      Int64
dtype: object

In [68]:
ps_clean[["Unit Price (USD)", "Quantity Available"]].isna().sum()

Unit Price (USD)      159
Quantity Available    153
dtype: int64

In [69]:
missing_price_indexes = ps_clean.index[
    ps_clean["Unit Price (USD)"].isna()
]

ps.loc[
    missing_price_indexes,
    [
        "Digi-Key Part Number",
        "Manufacturer Part Number",
        "Unit Price (USD)"
    ]
].head(15)

    Digi-Key Part Number Manufacturer Part Number Unit Price (USD)
12    785-L878E5434TR-ND            L-878E5434-TR              NaN
19     474-Q722P6863R-ND             Q-722P6863-R              NaN
37    894-LED393L9727-ND             LED-393L9727              NaN
42   713-SNS578K1043T-ND           SNS-578K1043-T              NaN
50      662-R406B596R-ND              R-406B596-R              TBD
71   588-MCU319D2199S-ND           MCU-319D2199-S              TBD
110  985-LED322Z6167S-ND           LED-322Z6167-S              NaN
117  360-IC547E7443TR-ND           IC-547E7443-TR               -
198  376-CBL817D5941R-ND           CBL-817D5941-R               -
258    286-K882D6741T-ND             K-882D6741-T              NaN
269    257-F885Z3578T-ND             F-885Z3578-T              TBD
334  129-SNS472Y1103T-ND           SNS-472Y1103-T              TBD
341  253-MCU362E4651S-ND           MCU-362E4651-S              TBD
407   100-L796X6060TR-ND            L-796X6060-TR              NaN
417  258-SNS473K2151R-ND           SNS-473K2151-R              NaN

In [70]:
# Identify text columns
text_columns = ps_clean.select_dtypes(
    include=["object", "string"]
).columns

# Remove extra spaces and standardize missing values
for col in text_columns:
    ps_clean[col] = ps_clean[col].astype("string").str.strip()

    ps_clean[col] = ps_clean[col].replace(
        [
            "", "N/A", "NA", "n/a", "na",
            "NaN", "nan", "None", "null",
            "<NA>", "TBD", "tbd"
        ],
        pd.NA
    )

print("Text cleaning completed!")

Text cleaning completed!

In [71]:
ps_clean.isna().sum().sort_values(ascending=False)

Unit Price (USD)                159
Quantity Available              153
Description                      87
Manufacturer                     69
Product Category                 58
Manufacturer Part Number         57
Package / Case                   52
Digi-Key Part Number             50
RoHS Status                       0
Minimum Order Qty                 0
Currency                          0
Product URL                       0
Datasheet URL                     0
Last Updated                      0
Warehouse                         0
Missing Digi-Key Part Number      0
dtype: int64

In [72]:
print("Rows:", ps_clean.shape[0])
print("Columns:", ps_clean.shape[1])

ps_clean.head()

Rows: 4900
Columns: 16

,Digi-Key Part Number,Manufacturer Part Number,Manufacturer,Description,Quantity Available,Unit Price (USD),Product Category,Package / Case,RoHS Status,Minimum Order Qty,Currency,Product URL,Datasheet URL,Last Updated,Warehouse,Missing Digi-Key Part Number
0,144-PS215M6233T-ND,PS-215M6233-T,Phoenix Contact,POWER MODULE 24V 40W,0,42.3225,Power Supplies,Axial,Unknown,100,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/ps_215m6233_t.pdf,2026-02-26,US West,False
1,465-PS258F5394R-ND,PS-258F5394-R,Molex,POWER MODULE 24V 40W,733,0.2753,Power Supplies,QFP-48,RoHS Compliant,1,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/ps_258f5394_r.pdf,2024-04-11,EU Central,False
2,169-C260U8249T-ND,C-260U8249-T,Infineon Technologies,CAP CER 0.1UF 50V X7R ±1%,0,1.7535,Capacitors,SOD-123,Not Applicable,5,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/c_260u8249_t.pdf,2025-10-04,US East,False
3,467-D947N2192R-ND,D-947N2192-R,Würth Elektronik,TVS DIODE 5V UNIDIR,0,7.0559,Diodes,SMA,Not Applicable,1,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/d_947n2192_r.pdf,2024-07-03,US West,False
4,956-OP719P9865S-ND,OP-719P9865-S,Murata Electronics,IC OPAMP GP 1 CIRCUIT 5SOT-23,0,93.5672,Operational Amplifiers,SMA,Unknown,25,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/op_719p9865_s.pdf,2025-01-17,Asia Pacific,False

In [73]:
duplicate_parts_count = (
    ps_clean["Digi-Key Part Number"]
    .dropna()
    .duplicated()
    .sum()
)

print("Duplicate Part Numbers:", duplicate_parts_count)

Duplicate Part Numbers: 0

In [74]:
duplicate_parts = ps_clean[
    ps_clean["Digi-Key Part Number"].notna()
    & ps_clean["Digi-Key Part Number"].duplicated(keep=False)
].sort_values("Digi-Key Part Number")

duplicate_parts.head(20)

Empty DataFrame
Columns: [Digi-Key Part Number, Manufacturer Part Number, Manufacturer, Description, Quantity Available, Unit Price (USD), Product Category, Package / Case, RoHS Status, Minimum Order Qty, Currency, Product URL, Datasheet URL, Last Updated, Warehouse, Missing Digi-Key Part Number]
Index: []

In [75]:
print("Current rows:", len(ps_clean))
print("Current columns:", len(ps_clean.columns))

print("\nMissing values:")
print(ps_clean.isna().sum().sort_values(ascending=False))

Current rows: 4900
Current columns: 16

Missing values:
Unit Price (USD)                159
Quantity Available              153
Description                      87
Manufacturer                     69
Product Category                 58
Manufacturer Part Number         57
Package / Case                   52
Digi-Key Part Number             50
RoHS Status                       0
Minimum Order Qty                 0
Currency                          0
Product URL                       0
Datasheet URL                     0
Last Updated                      0
Warehouse                         0
Missing Digi-Key Part Number      0
dtype: int64

In [76]:
ps_clean.columns = (
    ps_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(r"[^a-z0-9]+", "_", regex=True)
    .str.strip("_")
)

ps_clean.columns.tolist()

['digi_key_part_number',
 'manufacturer_part_number',
 'manufacturer',
 'description',
 'quantity_available',
 'unit_price_usd',
 'product_category',
 'package_case',
 'rohs_status',
 'minimum_order_qty',
 'currency',
 'product_url',
 'datasheet_url',
 'last_updated',
 'warehouse',
 'missing_digi_key_part_number']

In [77]:
print("Rows:", ps_clean.shape[0])
print("Columns:", ps_clean.shape[1])

ps_clean.head()

Rows: 4900
Columns: 16

,digi_key_part_number,manufacturer_part_number,manufacturer,description,quantity_available,unit_price_usd,product_category,package_case,rohs_status,minimum_order_qty,currency,product_url,datasheet_url,last_updated,warehouse,missing_digi_key_part_number
0,144-PS215M6233T-ND,PS-215M6233-T,Phoenix Contact,POWER MODULE 24V 40W,0,42.3225,Power Supplies,Axial,Unknown,100,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/ps_215m6233_t.pdf,2026-02-26,US West,False
1,465-PS258F5394R-ND,PS-258F5394-R,Molex,POWER MODULE 24V 40W,733,0.2753,Power Supplies,QFP-48,RoHS Compliant,1,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/ps_258f5394_r.pdf,2024-04-11,EU Central,False
2,169-C260U8249T-ND,C-260U8249-T,Infineon Technologies,CAP CER 0.1UF 50V X7R ±1%,0,1.7535,Capacitors,SOD-123,Not Applicable,5,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/c_260u8249_t.pdf,2025-10-04,US East,False
3,467-D947N2192R-ND,D-947N2192-R,Würth Elektronik,TVS DIODE 5V UNIDIR,0,7.0559,Diodes,SMA,Not Applicable,1,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/d_947n2192_r.pdf,2024-07-03,US West,False
4,956-OP719P9865S-ND,OP-719P9865-S,Murata Electronics,IC OPAMP GP 1 CIRCUIT 5SOT-23,0,93.5672,Operational Amplifiers,SMA,Unknown,25,USD,https://example.com/digikey-practice/products/...,https://example.com/datasheets/op_719p9865_s.pdf,2025-01-17,Asia Pacific,False

In [78]:
print("Negative prices:",
      ps_clean["unit_price_usd"].lt(0).sum())

print("Zero prices:",
      ps_clean["unit_price_usd"].eq(0).sum())

print("Negative quantities:",
      ps_clean["quantity_available"].lt(0).sum())

print("Zero quantities:",
      ps_clean["quantity_available"].eq(0).sum())

Negative prices: 0
Zero prices: 0
Negative quantities: 0
Zero quantities: 1874

In [79]:
invalid_values = ps_clean[
    (ps_clean["unit_price_usd"] < 0) |
    (ps_clean["quantity_available"] < 0)
]

invalid_values[
    [
        "digi_key_part_number",
        "manufacturer",
        "unit_price_usd",
        "quantity_available"
    ]
]

Empty DataFrame
Columns: [digi_key_part_number, manufacturer, unit_price_usd, quantity_available]
Index: []

In [80]:
id_columns = [
    "digi_key_part_number",
    "manufacturer_part_number"
]

missing_both_ids = ps_clean[
    ps_clean[id_columns].isna().all(axis=1)
]

print("Rows missing both identifiers:", len(missing_both_ids))

Rows missing both identifiers: 0

In [81]:
missing_both_ids[
    [
        "manufacturer",
        "description",
        "unit_price_usd",
        "quantity_available"
    ]
].head(10)

Empty DataFrame
Columns: [manufacturer, description, unit_price_usd, quantity_available]
Index: []

In [82]:
missing_dkpn = ps_clean[
    ps_clean["digi_key_part_number"].isna()
]

print("Missing Digi-Key Part Numbers:", len(missing_dkpn))

print(
    "Manufacturer Part Number available:",
    missing_dkpn["manufacturer_part_number"].notna().sum()
)

Missing Digi-Key Part Numbers: 50
Manufacturer Part Number available: 50

In [83]:
missing_dkpn[
    [
        "digi_key_part_number",
        "manufacturer_part_number",
        "manufacturer",
        "description"
    ]
].head(10)

,digi_key_part_number,manufacturer_part_number,manufacturer,description
44,<NA>,PS-TEST0013,Littelfuse,AC/DC CONVERTER 12V 2A
233,<NA>,L-TEST0028,EPCOS,FIXED IND 47UH 750MA
532,<NA>,SW-TEST0048,Vishay,SWITCH SLIDE SPDT 300MA
598,<NA>,XTAL-TEST0020,ROHM Semiconductor,CRYSTAL 16MHZ 18PF SMD
675,<NA>,LED-TEST0029,STMicroelectronics,LED BLUE 470NM THROUGH HOLE
681,<NA>,XTAL-TEST0044,Nichicon,CRYSTAL 16MHZ 18PF SMD
683,<NA>,F-TEST0031,Würth Elektronik,FUSE BOARD MOUNT 2A 250V
721,<NA>,J-TEST0041,Molex,CONN TERMINAL BLOCK 3POS
743,<NA>,F-TEST0022,STMicroelectronics,RESETTABLE PTC 500MA
744,<NA>,MCU-TEST0023,Bourns,IC MCU 32BIT 128KB FLASH 48LQFP

In [84]:
important_columns = [
    "digi_key_part_number",
    "manufacturer_part_number",
    "unit_price_usd",
    "quantity_available"
]

ps_clean[important_columns].isna().sum()

digi_key_part_number         50
manufacturer_part_number     57
unit_price_usd              159
quantity_available          153
dtype: int64

In [85]:
missing_price_quantity = ps_clean[
    ps_clean["unit_price_usd"].isna()
    | ps_clean["quantity_available"].isna()
]

missing_price_quantity[
    [
        "digi_key_part_number",
        "manufacturer_part_number",
        "unit_price_usd",
        "quantity_available"
    ]
].head(10)

,digi_key_part_number,manufacturer_part_number,unit_price_usd,quantity_available
12,785-L878E5434TR-ND,L-878E5434-TR,<NA>,0
19,474-Q722P6863R-ND,Q-722P6863-R,<NA>,0
37,894-LED393L9727-ND,LED-393L9727,<NA>,380142
42,713-SNS578K1043T-ND,SNS-578K1043-T,<NA>,50
44,<NA>,PS-TEST0013,1.25,<NA>
50,662-R406B596R-ND,R-406B596-R,<NA>,0
71,588-MCU319D2199S-ND,MCU-319D2199-S,<NA>,52949
110,985-LED322Z6167S-ND,LED-322Z6167-S,<NA>,10
117,360-IC547E7443TR-ND,IC-547E7443-TR,<NA>,5844
143,546-R146E8745R-ND,R-146E8745-R,0.4929,<NA>

In [86]:
print("Total rows:", len(ps_clean))
print("Total columns:", len(ps_clean.columns))
print("Exact duplicate rows:", ps_clean.duplicated().sum())

Total rows: 4900
Total columns: 16
Exact duplicate rows: 0

In [87]:
ps_clean["last_updated"].head(10)

0   2026-02-26
1   2024-04-11
2   2025-10-04
3   2024-07-03
4   2025-01-17
5   2023-10-17
6   2026-06-04
7   2024-12-21
8   2025-11-13
9   2026-08-26
Name: last_updated, dtype: datetime64[ns]

In [88]:
ps_clean["last_updated"].dtype

dtype('<M8[ns]')

In [89]:
ps_clean["last_updated"] = pd.to_datetime(
    ps_clean["last_updated"],
    errors="coerce"
)

In [90]:
print("Date data type:", ps_clean["last_updated"].dtype)

print(
    "Missing or invalid dates:",
    ps_clean["last_updated"].isna().sum()
)

Date data type: datetime64[ns]
Missing or invalid dates: 0

In [91]:
print("Total Rows:", ps_clean.shape[0])
print("Total Columns:", ps_clean.shape[1])

print("Exact Duplicate Rows:", ps_clean.duplicated().sum())

Total Rows: 4900
Total Columns: 16
Exact Duplicate Rows: 0

In [92]:
quality_report = pd.DataFrame({
    "Data Type": ps_clean.dtypes.astype(str),
    "Missing Values": ps_clean.isna().sum(),
    "Missing Percentage": (ps_clean.isna().mean() * 100).round(2),
    "Unique Values": ps_clean.nunique()
})

quality_report

,Data Type,Missing Values,Missing Percentage,Unique Values
digi_key_part_number,string,50,1.02,4850
manufacturer_part_number,string,57,1.16,4843
manufacturer,string,69,1.41,28
description,string,87,1.78,110
quantity_available,Int64,153,3.12,1993
unit_price_usd,Float64,159,3.24,3879
product_category,string,58,1.18,18
package_case,string,52,1.06,15
rohs_status,string,0,0.00,4
minimum_order_qty,int64,0,0.00,5
currency,string,0,0.00,1
product_url,string,0,0.00,4900
datasheet_url,string,0,0.00,4900
last_updated,datetime64[ns],0,0.00,1315
warehouse,string,0,0.00,5
missing_digi_key_part_number,bool,0,0.00,2

In [93]:
print(
    "Negative Prices:",
    ps_clean["unit_price_usd"].lt(0).sum()
)

print(
    "Negative Quantities:",
    ps_clean["quantity_available"].lt(0).sum()
)

Negative Prices: 0
Negative Quantities: 0

In [94]:
ps_clean.to_csv("digikey_cleaned.csv", index=False)

print("Cleaned file exported successfully!")

Cleaned file exported successfully!

In [95]:
from google.colab import files

files.download("digikey_cleaned.csv")

In [96]:
print("Total Rows:", ps_clean.shape[0])
print("Total Columns:", ps_clean.shape[1])

print("Exact Duplicate Rows:", ps_clean.duplicated().sum())

Total Rows: 4900
Total Columns: 16
Exact Duplicate Rows: 0

In [97]:
quality_report = pd.DataFrame({
    "Data Type": ps_clean.dtypes.astype(str),
    "Missing Values": ps_clean.isna().sum(),
    "Missing Percentage": (
        ps_clean.isna().mean() * 100
    ).round(2),
    "Unique Values": ps_clean.nunique()
})

quality_report

,Data Type,Missing Values,Missing Percentage,Unique Values
digi_key_part_number,string,50,1.02,4850
manufacturer_part_number,string,57,1.16,4843
manufacturer,string,69,1.41,28
description,string,87,1.78,110
quantity_available,Int64,153,3.12,1993
unit_price_usd,Float64,159,3.24,3879
product_category,string,58,1.18,18
package_case,string,52,1.06,15
rohs_status,string,0,0.00,4
minimum_order_qty,int64,0,0.00,5
currency,string,0,0.00,1
product_url,string,0,0.00,4900
datasheet_url,string,0,0.00,4900
last_updated,datetime64[ns],0,0.00,1315
warehouse,string,0,0.00,5
missing_digi_key_part_number,bool,0,0.00,2

In [98]:
ps_clean.to_csv("digikey_cleaned.csv", index=False)

print("Cleaned CSV file created successfully!")

Cleaned CSV file created successfully!

In [99]:
from google.colab import files

files.download("digikey_cleaned.csv")